version: "3.7"
services:

    jenkins.master:
        build:
            context: .
            dockerfile: ./master/Dockerfile
        container_name: jenkins-master
        privileged: true
        restart: always
        ports:
            - "8080:8080"
            - "8443:8443"
            - "50000:50000"
        volumes:
            - ./master/data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock